controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    comau_hw_control_loop:
      type: joint_trajectory_controller/JointTrajectoryController #comau_hardware_control_loop::ComauHWControlLoop


comau_hw_control_loop:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity
